development:
  aws_access_key: AKIAJ4QHZ36HNIK4F76A
  aws_secret: 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
  s3_bucket_name: mosey.dev

test:
  aws_access_key: AKIAJ4QHZ36HNIK4F76A
  aws_secret: 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
  s3_bucket_name: mosey.test
    
stage:
  aws_access_key: AKIAJ4QHZ36HNIK4F76A
  aws_secret: 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
  s3_bucket_name: mosey.stage

production:
  aws_access_key: AKIAJ4QHZ36HNIK4F76A
  aws_secret: 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
  s3_bucket_name: mosey
